### PR TITLE
Update elgamal.tex

### PR DESCRIPTION
**Pull request by SaswatD27**
Creating a branch to work on this

### CODE REVIEW

**Comment by paniash** [comment]
@SaswatD27 Looks like only certain formatting changes were made. I'm converting this PR to a draft one. Feel free to let me know when you're done with your additions so that I can edit or add stuff as per our convenience.

**Comment by paniash** [comment]
I'll merge it when it's ready.

**Comment by SaswatD27** [comment]
Lovely, I am working on some AES rn and will finish off that slapping together bit, so to speak. Finish off that ElGamal security thing and then you can paste that here when we finally merge these

**Comment by paniash** [comment]
Since it's only formatting changes here, I'm closing it.

> Lovely, I am working on some AES rn and will finish off that slapping together bit, so to speak. Finish off that ElGamal security thing and then you can paste that here when we finally merge these

Awesome!

**Pull request closed without merging**
